#!/bin/sh
# /etc/init.d/goldeneye 

### BEGIN INIT INFO
# Provides:          goldeneye
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start the door watch
# Description:       Will start / stop a program at boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting goldeneye"
    # run application you want to start
    /projects/workspace/nicedoormat/dooreye
    echo "Started..."
    ;;
  stop)
    echo "Stopping goldeneye"
    # kill application you want to stop
    pkill -f main.py
    echo "Stopped"
    ;;
  *)
    echo "Usage: /etc/init.d/goldeneye {start|stop}"
    exit 1
    ;;
esac

exit 0
